spring:
  data:
    mongodb:
      uri: "mongodb://192.168.198.132:27017/mydb"
  rabbitmq:
    host: 192.168.198.132
    port: 5672
    username: admin
    password: 123456
    template:
      default-receive-queue: simple_queue
    virtual-host: qi
server:
  port: 80
